CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    username VARCHAR(32) NOT NULL COMMENT '用户名',
    nickname VARCHAR(64) NULL COMMENT '昵称',
    avatar VARCHAR(255) NULL COMMENT '头像地址',
    email VARCHAR(128) NULL COMMENT '邮箱',
    password_hash VARCHAR(100) NOT NULL COMMENT '密码哈希',
    experience INT NOT NULL DEFAULT 0 COMMENT '经验值',
    level_code VARCHAR(16) NOT NULL DEFAULT 'LV1' COMMENT '等级编码',
    rank_code VARCHAR(16) NOT NULL DEFAULT 'BRONZE' COMMENT '段位编码',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标识',
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';
